---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBW43SgaeeHkaE8WpchWFiDwsgEbMUUgX4dvYhLT58he4jXkt/dlL3zPXSosjFa5Zhl3v0RtWzVKZfzz5l8oiqc65KR/ofD8BV5GGC/oPCPBwe0p49Zb/Tj9IkDdOrreMKnUhmid0GdH04ZYMuFRUjA1PpIRij/mGXrzE9LNmkwoLt5HqvVL5h4D/r1ghlCasMJ8Vrn/YweFtMMqC4UoAWqmv4SmCj77FQ7+pRu4IBrIReF8CntoSG+nUQxEJTT9HEvkPh5AFgCn1krlZkF4gyli7jH2XfaTKUalzIOT9i7RqGeMtaGualNboPQco99DZbcdJ7xZ9M5w9qjnL8d25rcbtWn8SUc5kZmI2AVR/JyWlH3tlpBOnhnQyKFvLSfQCnBdmXOixRhfOhCb0AZYOB6BCGTroGHMenHVrju7XiSjbeuTbf+/XfvcmHnYzV1gBIMVdDD1SS/ph4MxS+OW/BVijELDFmwMGGz38VxywKAVQMjpUtbfgTpFkvoKLurpvvT+AxOZ0nc6vGb08RcpeP1DeITyyQJIYIOF2mbJQh+Z8d+vh/r44E3ElzMxm6CSJjdVLvr1JtXSCJ1fkDb9+nPcUWVyxVvkQDQnXwnbtKBonq19D+bmloF7x2bBHFzQFWtSP1ZJadQKLHrvl1X0k3yH85PyKM40x7fXelJbBox0F6vzrQBxdmfBgG+40UUYQ6Y3IaYsLxuzHcJFgQeba23bLVjpg==
    admin-user: AgCB6IMcEcui9S7Oz5FJCgvzlAyKsL+datuVKa6RbfwaQo7zaAxYDrJHBBukXhTwfHVWLyvWpl0lY4LEN2aXOxySed/M419CE3RgjFyxUnQ5UBf4ertK6OG4RO7hiLIZOWLWASJoiTsUaanheg4OYF1eoy9cHFoORztAyGjobZdh+bwLtq26TFXJ6z2tpq8x3nd15HOv5Y1mrP6XQ629QClr542LHDcnljGYuVRw+teCc4ikkhvdkUtf1UaQsZdxCtXSV9XsYjLO8K0uw/Jj71eVnCxiE/3UefNVIzEChih8KdmnGF0BFBBZjfh+xHB3b4nGL/Kpd9K6LAot8hMvVO9J2rMOXpoT2d09UWfLALbv3cajN27/PcnZzboA9Z7LLSSbzLNT9SjLYNSNmr/7UaaD4lbYfU/uLRR7+20AYCsRLkiz4aueTxGxzGkyf7p+jq58B6XNz42mCtHh6ueHt2P10su9VqeeDEjpa0OM9POx1bNUreaQh4q0ZMYanCdm1sJSZC3ciWNpQ1wtXQvxOkAZr0wP6/V469NTa2WDs6FnyounCz76AtDj8wjOMFxmgR6VwernGWmXBTH7bfJ6KOjmc3kVpNpkCj+X8m+St2Ar6wtHet1pFI+PyMAV2sJ/CBPxw5wXOyc1n++B67F7DEeXzxbgJ2rn55xkLtK3fcUDnvlplulhoYZnXXQdlneH6uFtfmjj5g==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
